<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/06/19 10:17:30

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://root@localhost/card',
), 'propel');
$this->databases['propel'] = $database;
