<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/06/19 17:02:17

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://root:localhost@localhost/card',
), 'propel');
$this->databases['propel'] = $database;
