<?php
// auto-generated by sfPropelAdmin
// date: 2014/06/11 09:31:06
?>
<td colspan="6">
  <?php echo __('Kategori <strong>%%nama%%</strong> adalah <i>%%deskripsi%%</i><br/>
yang dibuat pada %%created_at%% dan pernah dibuat pada %%updated_at%%<br/>
%%_barangnya%%', 
array('%%nama%%' => link_to($kategori->getNama(), 'kategori/edit?id='.$kategori->getId()),
'%%deskripsi%%' => $kategori->getDeskripsi(),
'%%created_at%%' => ($kategori->getCreatedAt() !== null && $kategori->getCreatedAt() !== '') ? format_date($kategori->getCreatedAt(), "d-M-yy") : '',
'%%updated_at%%' => ($kategori->getUpdatedAt() !== null && $kategori->getUpdatedAt() !== '') ? format_date($kategori->getUpdatedAt(), "f") : '',
'%%_barangnya%%' => get_partial('barangnya', array('type' => 'list', 'kategori' => $kategori)))) ?></td>