<?php
// auto-generated by sfPropelAdmin
// date: 2014/06/11 09:31:06
?>
    <td><?php echo $kategori->getNama() ?></td>
      <td><?php echo $kategori->getDeskripsi() ?></td>
      <td><?php echo $kategori->getNamaStrip() ?></td>
      <td><?php echo ($kategori->getCreatedAt() !== null && $kategori->getCreatedAt() !== '') ? format_date($kategori->getCreatedAt(), "d-M-yy") : '' ?></td>
      <td><?php echo ($kategori->getUpdatedAt() !== null && $kategori->getUpdatedAt() !== '') ? format_date($kategori->getUpdatedAt(), "f") : '' ?></td>
  