<?php
// auto-generated by sfPropelAdmin
// date: 2014/06/11 09:31:06
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'kategori/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
