<?php
// auto-generated by sfPropelAdmin
// date: 2014/06/11 09:31:06
?>
  <th id="sf_admin_list_th_nama">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/kategori/sort') == 'nama'): ?>
      <?php echo link_to(__('Nama'), 'kategori/list?sort=nama&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/kategori/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/kategori/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Nama'), 'kategori/list?sort=nama&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_deskripsi">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/kategori/sort') == 'deskripsi'): ?>
      <?php echo link_to(__('Deskripsi'), 'kategori/list?sort=deskripsi&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/kategori/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/kategori/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Deskripsi'), 'kategori/list?sort=deskripsi&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_nama_strip">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/kategori/sort') == 'nama_strip'): ?>
      <?php echo link_to(__('Nama strip'), 'kategori/list?sort=nama_strip&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/kategori/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/kategori/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Nama strip'), 'kategori/list?sort=nama_strip&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_created_at">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/kategori/sort') == 'created_at'): ?>
      <?php echo link_to(__('Dibuat Pada'), 'kategori/list?sort=created_at&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/kategori/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/kategori/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Dibuat Pada'), 'kategori/list?sort=created_at&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_updated_at">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/kategori/sort') == 'updated_at'): ?>
      <?php echo link_to(__('Updated at'), 'kategori/list?sort=updated_at&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/kategori/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/kategori/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Updated at'), 'kategori/list?sort=updated_at&type=asc') ?>
      <?php endif; ?>
          </th>
