<?php
// auto-generated by sfPropelAdmin
// date: 2014/06/11 09:31:05
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('edit kategori', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('kategori/edit_header', array('kategori' => $kategori)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('kategori/edit_messages', array('kategori' => $kategori, 'labels' => $labels)) ?>
<?php include_partial('kategori/edit_form', array('kategori' => $kategori, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('kategori/edit_footer', array('kategori' => $kategori)) ?>
</div>

</div>
