propel:
    kartu:
        id: ~
        point: integer
        file: varchar(255)
        keterangan: longvarchar
        created_at: ~
        updated_at: ~
    meja:
        id: ~
        baris: integer
        kolom: integer
        status: integer
        id_game: { type: integer, required: true, foreignTable: game, foreignReference: id }
        id_skill: { type: integer, required: true, foreignTable: kartu, foreignReference: id }
        created_at: ~
        updated_at: ~
    skill:
        id: ~
        nama: varchar(255)
        deskripsi: longvarchar
        created_at: ~
        updated_at: ~
    game:
        id: ~
        nama: varchar(255)
        status: integer
        created_at: ~
        updated_at: ~
    room:
        id: ~
        nama: varchar(255)
        jumlah: integer
        max: integer
        id_user: { type: integer, required: true, foreignTable: user, foreignReference: id }
        created_at: ~
        updated_at: ~
    user:
        id: ~
        username: varchar(255)
        password: varchar(255)
        nama: varchar(255)
        file: varchar(255)
        status: integer
        games: integer
        win: integer
        lose: integer
        point: integer
        id_room: { type: integer, required: true, foreignTable: room, foreignReference: id }
        id_sf: integer
        created_at: ~
        updated_at: ~
    user_game:
        id_user: { type: integer, required: true, foreignTable: user, foreignReference: id }
        id_game: { type: integer, required: true, foreignTable: game, foreignReference: id }
        HP: integer
        point: integer
        urutan: integer
        element: integer
        status: integer
    kartu_meja:
        id_meja: { type: integer, required: true, foreignTable: meja, foreignReference: id }
        id_kartu: { type: integer, required: true, foreignTable: kartu, foreignReference: id }
