<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/06/11 09:27:01

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://root:localhost@localhost/latihan_tki',
), 'propel');
$this->databases['propel'] = $database;
