<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/06/11 10:34:00
sfConfig::add(array(
  'app_pager_homepage_max' => 5,
  'app_sf_guard_plugin_profile_class' => 'Pegawai',
  'app_sf_guard_plugin_profile_field_name' => 'sf_guard_user_id',
  'app_servis_key' => 'janganbilangbilang',
));
