<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/06/15 11:34:34
$this->security = array (
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'lihat',
      ),
    ),
  ),
  'detail' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'lihat',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
