all:
  layout: layout

#this will apply login_layout to the loginSuccess view
indexSuccess:
  layout: login_layout
  stylesheets:    [bootstrap.css, custom.css, side.css, theme.bootstrap.css]

  javascripts:    [jq.js, bootstrap.js]


