generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Kategori
    theme:            default
    
    list:
      title: Daftar Kategori
      hide: [id]
      fields:
        created_at: { params: date_format='d-M-yy' , name: Dibuat Pada }
      layout: stacked
   
      params: |
        Kategori <strong>%%=nama%%</strong> adalah <i>%%deskripsi%%</i><br/>
        yang dibuat pada %%created_at%% dan pernah dibuat pada %%updated_at%%<br/>
        %%_barangnya%%
      filters: [nama, created_at ]
      max_per_page: 3
