default:
  http_metas:
    content-type: text/html

  metas:
    title:        symfony project
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [main, morrisBaru.css, bootstrap.min.css, sb-admin.css, font-awesome.css, dataTables.bootstrap.css, custom.css, alertify.css, alertify.default.css, daterangepicker-bs3.css ]

  javascripts:    [raphael.js, jqBaru.js, morrisBaru.js, bootstrap.min.js, jquery.metisMenu.js, sb-admin.js, dataTable.js, dataTables.bootstrap.js, prettify.js, alertify.js, moment.js, custom.js ]

  has_layout:     on
  layout:         layout
