default:
  http_metas:
    content-type: text/html

  metas:
    title:        symfony project
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [bootstrap.css]

  javascripts:    [jq.js, bootstrap.js, custom.js]


  has_layout:     on
  layout:         layout
